Edit LockCommand.class
hiddenite/hiddenite-locks pull request #1
Opened 2021-11-28 02:44 UTC by TheMisterObvious

Added the ability to add several people to a chest.

2021-11-28 16:55 UTC, TheMisterObvious commented
Updating locking system from Chest to Container with a configuration

2021-11-28 17:21 UTC, paul-maxime requested changes

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    	if (block.getState() instanceof Container && getConfig().getString("inventory-lockable").contains(block.getType().toString())) return true;
Il faudrait utiliser `getStringList` au lieu de `getString`, qui retourne un tableau au lieu d'une string.
On peut aussi remplacer `if (condition) return true; return false;` par `return condition;` directement.

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    	if (getConfig().getString("inventory-lockable").contains(inventoryType.toString())) return true;
On peut appeler cette fonction dans `isLockable` au dessus, ça évite d'écrire deux fois le même code.

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +        String log = "Player %s locked the %s %s:[%d, %d, %d].";
Le texte de `log` ne change jamais donc je ne vois pas l'intérêt de l'avoir déplacé dans une variable. :eyes:

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    		storage.lockContainer(invBlock.getBlock());
`storage.lockContainer(block);` directement fonctionne aussi, non ?

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +        String log = "Player %s unlocked the %s %s:[%d, %d, %d].";
Même remarque qu'au dessus dans `lockContainer`.

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    		storage.unlockContainer(invBlock.getBlock());
Même remarque qu'au dessus dans `lockContainer`.

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    		storage.setContainerUsers(invBlock.getBlock(), allowedUsers);
Même remarque que dans `lockContainer`, je pense qu'utiliser `block` directement fonctionne, non ?

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/commands/LockCommand.java
> +            plugin.sendMessage(player, "error-look-at-container");
Changer la configuration sans supporter les anciennes versions c'est mal vu en général, mais comme personne d'autre n'utilise ce plugin ça passe.

2021-11-28 17:21 UTC, paul-maxime commented on src/main/java/eu/hiddenite/locks/commands/LockCommand.java
> +            	OfflinePlayer targetPlayer = plugin.findExistingPlayer(targetedPlayer);
Pourquoi créer le tableau `targetedPlayers` quand on peut juste boucler sur `args` et utiliser `args[i]` ?

2021-11-28 17:21 UTC, paul-maxime commented on src/main/resources/config.yml
> +  lock-success: "§bcontainer locked. Use §a/unlock§b to unlock it and §a/lock + <player1> <player2>...§b to add other players."
J'aurais écrit `<players>` à la place de `<player1> <player2>...`, c'est pas aussi précis mais c'est plus court et les gens comprennent je pense.

2021-11-28 18:37 UTC, TheMisterObvious commented on src/main/java/eu/hiddenite/locks/LocksPlugin.java
> +    		storage.lockContainer(invBlock.getBlock());
`logBlock = block.getType().getString()` fonctionne aussi directement, merci.

2021-11-28 18:43 UTC, TheMisterObvious commented on src/main/java/eu/hiddenite/locks/commands/LockCommand.java
> +            plugin.sendMessage(player, "error-look-at-container");
Pour ça il suffirait de mettre `plugin.sendMessage(player, "error-look-at-container" || "error-look-at-chest");` non ?

2021-11-28 18:46 UTC, TheMisterObvious commented on src/main/java/eu/hiddenite/locks/commands/LockCommand.java
> +            	OfflinePlayer targetPlayer = plugin.findExistingPlayer(targetedPlayer);
Pour moi cela me paraissait logique de faire comme ça mais effectivement c'est inutile, j'ai fait ce code entre 3h et 8h du matin, je n'étais pas dans les meilleurs conditions pour réfléchir.

2021-11-28 19:14 UTC, TheMisterObvious commented on src/main/resources/config.yml
> +  lock-success: "§bcontainer locked. Use §a/unlock§b to unlock it and §a/lock + <player1> <player2>...§b to add other players."
J'y avait pensé et je ne trouvais pas ça très logique mais je pense que les gens pourrais comprendre.

2021-11-30 18:46 UTC, TheMisterObvious commented
Fait.

2021-12-07 20:43 UTC, closed without merging